// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmhvtdiggkdzmbyzgsuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtaHZ0ZGlnZ2tkem1ieXpnc3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDk5NzMsImV4cCI6MjA2NjcyNTk3M30.6ACmFnw-E7xYhox7wsHbjIPWbdNHworxBP6Nv0IQy38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);